In [2]:
import pandas as pd

data = pd.read_csv(r"C:\Users\kdhakal\PycharmProjects\Generative-AI-LLM\dataset\spam.csv", encoding="latin1")

In [3]:
data

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,NaN,NaN,NaN
5568,ham,Will Ì_ b going to esplanade fr home?,NaN,NaN,NaN
5569,ham,"Pity, * was in mood for that. So...any other s...",NaN,NaN,NaN
5570,ham,The guy did some bitching but I acted like i'd...,NaN,NaN,NaN
5571,ham,Rofl. Its true to its name,NaN,NaN,NaN

In [4]:
## Data Cleaning and Preprocessing

In [5]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kdhakal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [6]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [8]:
data['lowercase'] = data['v2'].str.lower();

In [9]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4,lowercase
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,"go until jurong point, crazy.. available only ..."
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,ok lar... joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,u dun say so early hor... u c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,"nah i don't think he goes to usf, he lives aro..."

In [10]:
data = data[['v1', 'v2', 'lowercase']].rename(columns={'v1': 'category', 'v2': 'message'})

In [11]:
data.head()

,category,message,lowercase
0,ham,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ..."
1,ham,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro..."

In [12]:
#removing stopwords
en_stopwords = stopwords.words('english')

data['no_stopwords'] = data['lowercase'].apply(lambda x : ' '.join([word for word in x.split() if word not in en_stopwords]))

In [13]:
data.head()

,category,message,lowercase,no_stopwords
0,ham,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ...","go jurong point, crazy.. available bugis n gre..."
1,ham,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...,u dun say early hor... u c already say...
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro...","nah think goes usf, lives around though"

In [14]:
#punctation removal
data['no_stopwords_no_punct'] = data['no_stopwords'].str.replace('[^a-zA-Z]','')

In [15]:
data.head()

,category,message,lowercase,no_stopwords,no_stopwords_no_punct
0,ham,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ...","go jurong point, crazy.. available bugis n gre...","go jurong point, crazy.. available bugis n gre..."
1,ham,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry 2 wkly comp win fa cup final tkts 2...,free entry 2 wkly comp win fa cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...,u dun say early hor... u c already say...,u dun say early hor... u c already say...
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro...","nah think goes usf, lives around though","nah think goes usf, lives around though"

In [16]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import spacy
import re
import pandas as pd

In [17]:
#tokenization
data['token_rw'] = data.apply(lambda x: word_tokenize(x['message']), axis=1)
data['token_clean_data'] = data.apply(lambda x : word_tokenize(x['no_stopwords_no_punct']), axis=1)

In [18]:
data.head()

,category,message,lowercase,no_stopwords,no_stopwords_no_punct,token_rw,token_clean_data
0,ham,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ...","go jurong point, crazy.. available bugis n gre...","go jurong point, crazy.. available bugis n gre...","[Go, until, jurong, point, ,, crazy, .., Avail...","[go, jurong, point, ,, crazy, .., available, b..."
1,ham,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...,"[Ok, lar, ..., Joking, wif, u, oni, ...]","[ok, lar, ..., joking, wif, u, oni, ...]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry 2 wkly comp win fa cup final tkts 2...,free entry 2 wkly comp win fa cup final tkts 2...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[free, entry, 2, wkly, comp, win, fa, cup, fin..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...,u dun say early hor... u c already say...,u dun say early hor... u c already say...,"[U, dun, say, so, early, hor, ..., U, c, alrea...","[u, dun, say, early, hor, ..., u, c, already, ..."
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro...","nah think goes usf, lives around though","nah think goes usf, lives around though","[Nah, I, do, n't, think, he, goes, to, usf, ,,...","[nah, think, goes, usf, ,, lives, around, though]"

In [19]:
#lemmatizing
lemmatizer = WordNetLemmatizer()
data['token_clean_lemmatized'] = data['token_clean_data'].apply(lambda tokens: [lemmatizer.lemmatize(token) for token in tokens])
data.head()

,category,message,lowercase,no_stopwords,no_stopwords_no_punct,token_rw,token_clean_data,token_clean_lemmatized
0,ham,"Go until jurong point, crazy.. Available only ...","go until jurong point, crazy.. available only ...","go jurong point, crazy.. available bugis n gre...","go jurong point, crazy.. available bugis n gre...","[Go, until, jurong, point, ,, crazy, .., Avail...","[go, jurong, point, ,, crazy, .., available, b...","[go, jurong, point, ,, crazy, .., available, b..."
1,ham,Ok lar... Joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...,ok lar... joking wif u oni...,"[Ok, lar, ..., Joking, wif, u, oni, ...]","[ok, lar, ..., joking, wif, u, oni, ...]","[ok, lar, ..., joking, wif, u, oni, ...]"
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry in 2 a wkly comp to win fa cup fina...,free entry 2 wkly comp win fa cup final tkts 2...,free entry 2 wkly comp win fa cup final tkts 2...,"[Free, entry, in, 2, a, wkly, comp, to, win, F...","[free, entry, 2, wkly, comp, win, fa, cup, fin...","[free, entry, 2, wkly, comp, win, fa, cup, fin..."
3,ham,U dun say so early hor... U c already then say...,u dun say so early hor... u c already then say...,u dun say early hor... u c already say...,u dun say early hor... u c already say...,"[U, dun, say, so, early, hor, ..., U, c, alrea...","[u, dun, say, early, hor, ..., u, c, already, ...","[u, dun, say, early, hor, ..., u, c, already, ..."
4,ham,"Nah I don't think he goes to usf, he lives aro...","nah i don't think he goes to usf, he lives aro...","nah think goes usf, lives around though","nah think goes usf, lives around though","[Nah, I, do, n't, think, he, goes, to, usf, ,,...","[nah, think, goes, usf, ,, lives, around, though]","[nah, think, go, usf, ,, life, around, though]"

## Ceate Bag of Word model

In [20]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True)

In [21]:
# Convert lemmatized tokens to text strings for Bag of Words
data['token_clean_lemmatized_text'] = data['token_clean_lemmatized'].apply(lambda tokens: ' '.join(tokens))
data[['token_clean_lemmatized', 'token_clean_lemmatized_text']].head()

,token_clean_lemmatized,token_clean_lemmatized_text
0,"[go, jurong, point, ,, crazy, .., available, b...","go jurong point , crazy .. available bugis n g..."
1,"[ok, lar, ..., joking, wif, u, oni, ...]",ok lar ... joking wif u oni ...
2,"[free, entry, 2, wkly, comp, win, fa, cup, fin...",free entry 2 wkly comp win fa cup final tkts 2...
3,"[u, dun, say, early, hor, ..., u, c, already, ...",u dun say early hor ... u c already say ...
4,"[nah, think, go, usf, ,, life, around, though]","nah think go usf , life around though"

In [22]:
# Create Bag of Words matrix
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500, binary=True)
X = cv.fit_transform(data['token_clean_lemmatized_text']).toarray()

bow_df = pd.DataFrame(X, columns=cv.get_feature_names_out())
bow_df.head()

,00,000,02,0207,03,04,05,06,07xxxxxxxxx,0800,...,yours,yourself,yr,yun,yup,zed,ì_,ìï,û_,ûò
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
# Encode target column
y = data['category'].map({'ham': 0, 'spam': 1})
y.head()

0    0
1    0
2    1
3    0
4    0
Name: category, dtype: int64

In [24]:
# Combine BoW features with target for further processing
final_bow_data = bow_df.copy()
final_bow_data['target'] = y
final_bow_data.head()

,00,000,02,0207,03,04,05,06,07xxxxxxxxx,0800,...,yourself,yr,yun,yup,zed,ì_,ìï,û_,ûò,target
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [25]:
# Example: split data for model training
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

X_train.shape, X_test.shape

((4457, 2500), (1115, 2500))

In [26]:
# Example: train a spam classifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

model = MultinomialNB()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9856502242152466
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       966
           1       0.97      0.92      0.94       149

    accuracy                           0.99      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115